repos:
  - repo: https://github.com/rapidsai/frigate/
    # need a release after https://github.com/rapidsai/frigate/pull/74
    rev: 0aca194f9011a656fd7211dbe2210511c94a36a5
    hooks:
      - id: frigate
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.12 #  pre-commit autoupdate  - to keep the version up to date
    hooks:
      - id: helmlint
