ARG kbatch_version=set-by-chartress
# for now, just retagging the image to match the chart
# but this could be where we translate config from helm 
FROM ghcr.io/kbatch-dev/kbatch-proxy:${kbatch_version}
